//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub use super::{
    leaderboard::Entity as Leaderboard, log_result::Entity as LogResult, user::Entity as User,
    user_from_steam::Entity as UserFromSteam,
};
